FROM maven:3.6.3-jdk-8-slim AS build
WORKDIR /home/app
COPY . /home/app
RUN mvn -f /home/app/pom.xml clean package

FROM openjdk:8-jdk-alpine
EXPOSE 8080
ARG JAR_FILE=target/order-processor-0.0.1-SNAPSHOT.jar
ADD ${JAR_FILE} order-processor-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/order-processor-0.0.1-SNAPSHOT.jar"]